# Generated by Django 3.2 on 2021-05-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('stock', models.CharField(choices=[('AVAILABLE,', 'Item Ready to be Purchased'), ('SOLD', 'Item Sold'), ('Restocking', 'Item will be Restocked in a few Days')], default='AVAILABLE', max_length=50)),
            ],
        ),
    ]
