# Generated by Django 3.2 on 2021-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='stock',
            field=models.CharField(choices=[('AVAILABLE ', 'Item Ready to be Sold'), ('SOLD', 'Item Soldout'), ('Restocking', 'Item will be Restocked in a few Days')], default='AVAILABLE', max_length=50),
        ),
    ]
